<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-06-08 14:50
=======
# Generated by Django 4.2.2 on 2023-07-01 06:12
>>>>>>> a77aecced6d01cf351118df2ea482b17fbe03da9

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
